### ISSUE TITLE
Portable Wired Charger Crash.

### ISSUE THREAD

**Issue by X-Niter** [FoxMcloud5655/Draconic-Additions#21]
java.lang.NullPointerException
    at com.brandon3055.brandonscore.lib.EnergyHelper.isEnergyTile(EnergyHelper.java:26)
    at net.foxmcloud.draconicadditions.items.tools.PortableWiredCharger.onItemRightClick(PortableWiredCharger.java:123)
    at net.minecraft.item.ItemStack.useItemRightClick(ItemStack.java:217)
    at net.minecraft.client.multiplayer.PlayerControllerMP.processRightClick(PlayerControllerMP.java:511)
    at net.optifine.override.PlayerControllerOF.processRightClick(PlayerControllerOF.java:80)
    at net.minecraft.client.Minecraft.rightClickMouse(Minecraft.java:1597)
    at net.minecraft.client.Minecraft.processKeyBinds(Minecraft.java:2254)
    at net.minecraft.client.Minecraft.runTickKeyboard(Minecraft.java:2020)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1808)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

I right-clicked the ground with it and it caused the crash. My guess was a possible null function that broke or is not working correctly? 
We will have to temporarily disable the item until further notice. 
Let me know any info on this. :)

**Comment by FoxMcloud5655** [comment]
I can't help but notice that you've got OptiFine...  I'm not sure if that is causing the crash or not, but I will look into this today.

**Comment by FoxMcloud5655** [comment]
Silly me...  I didn't check if the block even has a TileEntity attached to it before asking Brandon's Core if it's a valid energy source!

This is fixed in dev.
