### ISSUE TITLE
Infused Potato armor to Engergized Potato Armor issue

### ISSUE THREAD

**Issue by Micaxs** [FoxMcloud5655/Draconic-Additions#23]
Hello, when running this mod on a server I run into an issue when rightclicking the Infused Potato armor to change it to the Engergized Potato armor it reverts back when accessing any machine/inventory/table. It generates an error in the server as shown below:

Mod version: Draconic-Additions-1.12.2-1.11.0.31-universal.jar

```

16.04 22:53:47 [Server] Server thread/FATAL [minecraft/MinecraftServer]: Error executing task
--
530 | 16.04 22:53:47 [Server] INFO java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.item.ItemArmor.func_185083_B_()Lnet/minecraft/inventory/EntityEquipmentSlot;
531 | 16.04 22:53:47 [Server] INFO at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_242]
532 | 16.04 22:53:47 [Server] INFO at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_242]
533 | 16.04 22:53:47 [Server] INFO at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
534 | 16.04 22:53:47 [Server] INFO at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
535 | 16.04 22:53:47 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
536 | 16.04 22:53:47 [Server] INFO at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
537 | 16.04 22:53:47 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
538 | 16.04 22:53:47 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
539 | 16.04 22:53:47 [Server] INFO Caused by: java.lang.NoSuchMethodError: net.minecraft.item.ItemArmor.func_185083_B_()Lnet/minecraft/inventory/EntityEquipmentSlot;
540 | 16.04 22:53:47 [Server] INFO at net.foxmcloud.draconicadditions.items.armor.InfusedPotatoArmor.transformItem(InfusedPotatoArmor.java:81) ~[InfusedPotatoArmor.class:?]
541 | 16.04 22:53:47 [Server] INFO at net.foxmcloud.draconicadditions.items.armor.InfusedPotatoArmor.transformItem(InfusedPotatoArmor.java:76) ~[InfusedPotatoArmor.class:?]
542 | 16.04 22:53:47 [Server] INFO at net.foxmcloud.draconicadditions.items.armor.InfusedPotatoArmor.onItemRightClick(InfusedPotatoArmor.java:44) ~[InfusedPotatoArmor.class:?]
543 | 16.04 22:53:47 [Server] INFO at net.minecraft.item.ItemStack.useItemRightClick(ItemStack.java:217) ~[aip.class:?]
544 | 16.04 22:53:47 [Server] INFO at net.minecraft.server.management.PlayerInteractionManager.processRightClick(PlayerInteractionManager.java:358) ~[or.class:?]
545 | 16.04 22:53:47 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.processTryUseItem(NetHandlerPlayServer.java:765) ~[pa.class:?]
546 | 16.04 22:53:47 [Server] INFO at net.minecraft.network.play.client.CPacketPlayerTryUseItem.processPacket(SourceFile:32) ~[mb.class:?]
547 | 16.04 22:53:47 [Server] INFO at net.minecraft.network.play.client.CPacketPlayerTryUseItem.processPacket(SourceFile:9) ~[mb.class:?]
548 | 16.04 22:53:47 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
549 | 16.04 22:53:47 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_242]
550 | 16.04 22:53:47 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_242]
551 | 16.04 22:53:47 [Server] INFO at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
```

I want to add this is only when playing on a server, singeplayer this does not occur and everything works as expected. Is this a known issue and is there a possible fix for this?

Thanks.

**Comment by FoxMcloud5655** [comment]
Fixed in [7d2b9aa](https://github.com/FoxMcloud5655/Draconic-Additions/commit/7d2b9aad571f620a390d0fefeae2f4ecac482036).
