### ISSUE TITLE
minecraft is crashing when i use draconic additions

### ISSUE THREAD

**Issue by jackisgood99** [FoxMcloud5655/Draconic-Additions#49]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  GTCELoadingPlugin (gregtech-1.12.2-1.11.1.632.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.2.7.4.jar)
  LoadingPlugin (AdChimneys-1.12.2-3.5.15.0-build.0560.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  LogisticsPipesCoreLoader (logisticspipes-0.10.3.114.jar)
  CorePlugin (ForgeEndertech-1.12.2-4.5.5.0-build.0561.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.73-core.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  Techguns Core (techguns-1.12.2-2.0.2.0_pre3.1.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  LoadingPlugin (AdPother-1.12.2-1.2.17.0-build.0591.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 1/15/22 10:21 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Brandon's Core (brandonscore)
Caused by: java.lang.NoSuchMethodError: com.brandon3055.draconicevolution.client.creativetab.DETab.<init>(Ljava/lang/String;Ljava/lang/String;I)V
	at net.foxmcloud.draconicadditions.client.creativetab.DATab.<init>(DATab.java:19)
	at net.foxmcloud.draconicadditions.DAFeatures.<clinit>(DAFeatures.java:33)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.brandon3055.brandonscore.registry.ModFeatureParser.parseASMData(ModFeatureParser.java:76)
	at com.brandon3055.brandonscore.BrandonsCore.preInit(BrandonsCore.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by jackisgood99** [comment]
do you know why this is happening with draconic additions? normally i would be able to fix crash reports but i cant figure out whats broken here

**Comment by FoxMcloud5655** [comment]
Update Draconic Evolution and Brandon's Core.  You're out-of-date.
