### ISSUE TITLE
crash on boot [1.20.1]

### ISSUE THREAD

**Issue by Xplodin** [FoxMcloud5655/Draconic-Additions#61]
the error begins around here:
 [17Jun2024 08:35:55.033] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: draconicadditions, class net.foxmcloud.draconicadditions.DraconicAdditions
java.lang.NoSuchMethodError: 'void com.brandon3055.draconicevolution.api.DraconicAPI.addModuleProvider(java.lang.String)'
	at net.foxmcloud.draconicadditions.DraconicAdditions.<init>(DraconicAdditions.java:36) ~[Draconic-Additions-1.20.1-2.3.1.2-universal.jar%23965!/:1.20.1-2.3.1.2]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.2.19.jar%231404!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.2.19.jar%231403!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]

https://gist.github.com/Xplodin/fade796fc0ed5469d55382ce0dcc1406

the crashlog doesnt have anything so this is the debug.log

47.2.19
![image](https://github.com/FoxMcloud5655/Draconic-Additions/assets/13007677/ade38aaf-aeda-47c1-9cc5-99728acbae87)

**Comment by FoxMcloud5655** [comment]
Yeah, so the latest version of Draconic Evolution isn't actually out yet on CurseForge.  Give it a bit.
